### PR TITLE
Disable the local source

### PR DESCRIPTION
**Pull request by woksin**

### CODE REVIEW

**Comment by einari** [comment]
We are going to leave local source in. I've gone through and removed this disabling - it really screws with local development and having to remember to not check in. This seems to be an issue with AppVeyor - and is fixed for SDK now. So we should just get AppVeyor to work with this project as well.

**Comment by einari** [comment]
Looking at this; there is no AppVeyor build for this - so this shouldn't be a problem

**Comment by woksin** [comment]
I see, I was just confused since I saw that the packages that this Repo would push to Myget aren't there, so I assumed that the problem was that this solution failed on Appveyor build (we've had that exact problem before) and thus the packages never would be pushed to Myget. But I assume that this Appveyor pipeline has not been setup for this project just yet, and that's the reason that the packages aren't pushed

**Comment by einari** [comment]
I'll set it up now.

**Comment by woksin** [comment]
I was putting my fedora on, turning all the stones, trying to find where this Runtime.Events.Store.MongoDB package was coming from. Now I've solved the mystery :)

**Comment by einari** [comment]
Hehe.. Well spotted.  We need those packages later today - so thanks for the spotting.
We are now building and packages should arrive soon.

**Comment by woksin** [comment]
I will continue looking today, I have a feeling that there are more issues related to this

**Pull request closed without merging**
